<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "realurl_persistence"
 *
 * Auto generated by Extension Builder 2014-10-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Realurl persistence',
	'description' => 'Allows old realurl urls to still be valid even after they are expired.',
	'category' => 'plugin',
	'author' => 'Nils Blattner',
	'author_email' => 'nb@cabag.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.4',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.0-6.2.99',
			'realurl' => '1.10.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
